name: Bugs input
on:
  workflow_dispatch:
    inputs:
      bug_1_jira_link:
        description: Bug 1 Jira Link (e.g. https://paramount.atlassian.net/browse/CBSCOMDIS-5769)
        required: false
        type: string
      bug_1_description:
        description: Bug 1 Description (e.g. [AND][USA][MOBILE][P+] Error message on Support Page)
        required: false
        type: string
jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get info about bug 1
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.bug_1_jira_link != '' && startsWith(github.event.inputs.bug_1_jira_link, 'https://paramount.atlassian.net/')
        run: |
          BUG_1_JIRA_LINK="${{ inputs.bug_1_jira_link }}"
          BUG_1_DESCRIPTION="${{ inputs.bug_1_description }}"
          BUGS="<${BUG_1_JIRA_LINK}|${BUG_1_DESCRIPTION}>"
          echo "BUGS=${BUGS}" >> $GITHUB_ENV
      - name: Print bug info
        run: |
          echo "Sending Slack report with bug info: ${BUGS}"