name: Bugs input
on:
  workflow_dispatch:
    inputs:
      bug_1_jira_link:
        description: BUG 1 Jira Link (e.g. https://paramount.atlassian.net/browse/CBSCOMDIS-5769)
        required: false
        type: string
      bug_1_description:
        description: BUG 1 Description (e.g. [AND][USA][MOBILE][P+] Error message on Support Page)
        required: false
        type: string
      bug_2_jira_link:
        description: BUG 2 Jira Link (e.g. https://paramount.atlassian.net/browse/CBSCOMDIS-5769)
        required: false
        type: string
      bug_2_description:
        description: BUG 2 Description (e.g. [AND][USA][MOBILE][P+] Error message on Support Page)
        required: false
        type: string
      bug_3_jira_link:
        description: BUG 3 Jira Link (e.g. https://paramount.atlassian.net/browse/CBSCOMDIS-5769)
        required: false
        type: string
      bug_3_description:
        description: BUG 3 Description (e.g. [AND][USA][MOBILE][P+] Error message on Support Page)
        required: false
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up BUGS variable
        run: echo "BUGS=" >> $GITHUB_ENV

      - name: Get and append info about Bug 1
        if: startsWith(github.event.inputs.bug_1_description, '[AND]') && github.event.inputs.bug_1_jira_link != '' && startsWith(github.event.inputs.bug_1_jira_link, 'https://paramount.atlassian.net/')
        run: |
          BUG_1_JIRA_LINK="${{ github.event.inputs.bug_1_jira_link }}"
          BUG_1_DESCRIPTION="${{ github.event.inputs.bug_1_description }}"
          BUG_1_INFO="<${BUG_1_JIRA_LINK}|${BUG_1_DESCRIPTION}>"
          echo "BUGS=${BUG_1_INFO}" >> $GITHUB_ENV
        env:
          BUGS: ${{ env.BUGS }}

      - name: Append info about Bug 2
        if: startsWith(github.event.inputs.bug_2_description, '[AND]') && github.event.inputs.bug_2_jira_link != '' && startsWith(github.event.inputs.bug_2_jira_link, 'https://paramount.atlassian.net/')
        run: |
          BUG_2_JIRA_LINK="${{ github.event.inputs.bug_2_jira_link }}"
          BUG_2_DESCRIPTION="${{ github.event.inputs.bug_2_description }}"
          BUG_2_INFO="<${BUG_2_JIRA_LINK}|${BUG_2_DESCRIPTION}>"
          echo "BUGS=${{ env.BUGS }}\n${BUG_2_INFO}" >> $GITHUB_ENV
        env:
          BUGS: ${{ env.BUGS }}

      - name: Append info about Bug 3
        if: startsWith(github.event.inputs.bug_3_description, '[AND]') && github.event.inputs.bug_3_jira_link != '' && startsWith(github.event.inputs.bug_3_jira_link, 'https://paramount.atlassian.net/')
        run: |
          BUG_3_JIRA_LINK="${{ github.event.inputs.bug_3_jira_link }}"
          BUG_3_DESCRIPTION="${{ github.event.inputs.bug_3_description }}"
          BUG_3_INFO="<${BUG_3_JIRA_LINK}|${BUG_3_DESCRIPTION}>"
          echo "BUGS=${{ env.BUGS }}\n${BUG_3_INFO}" >> $GITHUB_ENV
        env:
          BUGS: ${{ env.BUGS }}

      - name: Print bug info
        run: |
          if [ -z "${{ env.BUGS }}" ]; then
            echo "EMPTY"
          else
            echo -e "Sending Slack report with bug info:\n${{ env.BUGS }}"
          fi
