name: Bugs input
on:
  workflow_dispatch:
    inputs:
      bug_1_jira_key:
        description: Bug 1 Jira key (e.g. CBSENTAPLS-3601)
        required: false
        type: string
      bug_1_description:
        description: Bug 1 Description (e.g. [APL][P+][US][iOS] Shows Details - PIN not shown when playing an extra clip)
        required: false
        type: string
jobs: 
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Send message
        run: echo "BUGS TICKETS WORKFLOW"

