name: First Workflow
on: workflow_dispatch #manually
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo "Hello worlds"
      - name: Print goodbye
        run: echo "Done - bye!"
    
