name: First Workflow
on: 
  pull_request:
    types:
      - opened
  workflow_dispatch:
  push:
    branches:
      - main
      - 'automation/**' #automation/CBENTSPNG
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print msgs
        run: |
          echo "Hello worlds 1"
          echo "Hello worlds 2"
    
