name: Fourth Workflow
on: push
env:
  MONGO_DB_NAME: ${{secrets.MONGO_DB_NAME}}
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Print msg
        run: echo "value is ${{env.MONGO_DB_NAME}}"